### ISSUE TITLE
请问缺少simple_pid是什么原因呢

### ISSUE THREAD

**Issue by gxxguoxingxing** [laszlo-schaffer/webots-szte-robocup-2022#1]
simple_pid需要怎么样添加进去呢
![Uploading image.png…]()

**Comment by laszlo-schaffer** [comment]
I do not speak chinese.

1. open a cmd terminal
2. pip install simple_pid

https://pypi.org/project/simple-pid/

**Comment by gxxguoxingxing** [comment]
thank you so much
